<?php echo $this->doctype(); ?>

<html lang="ru">
<head>
<meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',));
        ?>

    </head>
    <body>
        <?php $partial = array('application/navigation/topnav.phtml', 'default') ?>
        <?php $this->navigation('navigation')->menu()->setPartial($partial) ?>
        <?php echo $this->navigation('navigation')->menu()->render() ?>
                         
        <div class="container-fluid">
            <?php echo $this->content; ?>

		</div>
	<!-- /container -->	
	<footer>
		<p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
	</footer>
        <?php echo $this->inlineScript()?>
    </body>
</html>
