<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      
                    <?php foreach ($this->container as $page) : ?>
                    <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
                    <?php // when using partials we need to manually check for ACL conditions ?>
                    <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; } ?>
                    <?php $hasChildren = $page->hasPages(); ?>
                    <?php if (!$hasChildren): ?>
                    <li>
                        <a href="<?php echo $page->getHref() ?>">
                            <?php echo $this->translate($page->getLabel())?>
                        </a>
                    </li>
                    <?php else: ?>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?php echo $this->translate($page->getLabel()) ?><span class="caret"></span>
                            </a>
                                <ul class="dropdown-menu" role="menu">
                                <?php foreach ($page->getPages() as $child) : ?>
                                <?php // when using partials we need to manually check for ACL conditions ?>
                                <?php if(!$child->isVisible() || !$this->navigation()->accept($child)) { continue; } ?>
                                        <li>
                                             <a href="<?php echo $child->getHref() ?>">
                                                <?php echo $this->translate($child->getLabel())?>
                                            </a>
                                        </li>
                              <?php endforeach ?>
                             </ul>
                         </li>
                      <?php endif; ?>
                 <?php endforeach ?>
      </ul>
      
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
      <ul class="nav navbar-nav navbar-right">
           <li>
            <!-- Test if the User is connected -->
                <?php if(!$this->zfcUserIdentity()): ?>
                <!-- display the login link -->
                <a href="" data-toggle="modal" data-target="#loginModal">Sign In</a>
                <?php else: ?>
                <!-- display the 'display name' of the user -->
                    <?php echo $this->translate('Logged in as '); ?>
                        <a href="/account">
                            <?php echo $this->zfcUserIdentity()->getDisplayname(); ?>
                        </a>
                <?php endif?>
                 </li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>                    



<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="100" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>

      </div>
      <div class="modal-body">
        <?php echo $this->zfcUserLoginWidget(); ?>
      </div>
      <!--div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div-->
    </div>
  </div>
</div>


<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
            <h4 class="modal-title" id="myModalLabel"><?php echo $this->translate('Sign in'); ?></h4>
            </div>
            <div class="modal-body">
                <?php echo $this->zfcUserLoginWidget(); ?>
            </div>
            <!--  
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
        </div>-->
    </div>
  </div>
</div>