<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed"
				data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span> <span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="#">Brand</a>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
                    <?php foreach ($this->container as $page) : ?>
                    <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
                    <?php // when using partials we need to manually check for ACL conditions ?>
                    <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) { continue; } //здесь можно пропустить юзеровское меню?> 
                    <?php $hasChildren = $page->hasPages(); ?>
                    <?php if (!$hasChildren): ?>
                    <li><a href="<?php echo $page->getHref() ?>">
                            <?php echo $this->translate($page->getLabel())?>
                        </a>
                    </li>
                    <?php else: ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <?php echo $this->translate($page->getLabel()) ?>
                                    <span class="caret"></span>
                                </a>
        					       <ul class="dropdown-menu" role="menu">
                                        <?php foreach ($page->getPages() as $child) : ?>
                                        <?php // when using partials we need to manually check for ACL conditions ?>
                                        <?php if(!$child->isVisible() || !$this->navigation()->accept($child)) { continue; } ?>
                                                <li>
                                                    <a href="<?php echo $child->getHref() ?>">
                                                        <?php echo $this->translate($child->getLabel())?>
                                                    </a>
                                                 </li>
                                        <?php endforeach ?>
                                     </ul>
                             </li>
                      <?php endif; ?>
                 <?php endforeach ?>
			</ul>
			
            <!-- User right aligned navigation -->
            <?php $partial = array('zfc-user/user/navigation/usernav.phtml', 'account'); ?>
            <?php $this->navigation('user_navigation')->menu()->setPartial($partial); ?>
            <?php echo $this->navigation('user_navigation')->menu()->render(); ?>
            <!-- /User navigation -->
            
		</div>
		<!-- /.navbar-collapse -->
	</div>
	<!-- /.container-fluid -->
</nav>
